name: donateinfo
main: net.indecton.donateinfo.donateinfo
version: 1.0
website: http://indecton.net/
author: dredge20
commands:
  donate:
    description: View donation information
permissions:
  donateinfo.reload:
    default: op
  donateinfo.*:
    default: op
    children:
      donateinfo.reload: true
